### ISSUE TITLE
Player is required

### ISSUE THREAD

**Issue by Laxystem** [Gaming32/kilo-engine#2]
*This is DanielGolan's alt*

Currently, the player is _required_ for the game to run (`KiloEngineGame.kt` line `83`). Please, allow me to define my own camera behavior, or to ignore it completely.

**Comment by Gaming32** [comment]
A decent amount of the player code is actually hardcoded into the main loop, so that needs fixing first.

**Comment by Gaming32** [comment]
Oh uh, this is fixed now.

**Comment by Laxystem** [comment]
Amazing, did you release on maven?

**Comment by Gaming32** [comment]
Yep

**Comment by Laxystem** [comment]
> Yep

did you push it to the same version, 0.1-SNAPSHOT? please don't do that again, I have to delete stuff so gradle will re-build the project... next time do 0.1.1 or 0.2 or something, ok?

**Comment by Gaming32** [comment]
The whole point of SNAPSHOTs is that they stick on the same version and don't switch numbers. See https://stackoverflow.com/a/32654639 on how to refresh dependencies.

**Comment by Laxystem** [comment]
> The whole point of SNAPSHOTs is that they stick on the same version and don't switch numbers. See https://stackoverflow.com/a/32654639 on how to refresh dependencies.

Ah, alright. Didn't know that. Yeah, figured out how to refresh Gradle the moment after I commented....
