### ISSUE TITLE
Player is required in order for the scene to generate

### ISSUE THREAD

**Issue by Laxystem** [Gaming32/kilo-engine#9]
With player:
```json5
{
  skybox: [0.17, 0.18, 0.19],
    entities: [
      // What's a level without some entities, eh?
      // More details on entity Json5 syntax below in the "Entities" section.
      {
        position: [0, 1.4, -5],
        components: [
          {
            type: "capsuleCollider",
            radius: 0.4,
            length: 1
          },
          "player",
          {
            type: "camera",
            offset: [0, 0.7, 0]
          }
        ]
      }
    ]
}
```
![image](https://user-images.githubusercontent.com/127752744/226179033-b77655db-86f8-4c87-a546-9b4a1f8106ba.png)
Without player:
```json5
{
  skybox: [0.17, 0.18, 0.19],
  entities: []
}
```
![image](https://user-images.githubusercontent.com/127752744/226179130-d9ccc626-dd6c-4b30-95ff-abe0dff3fcdc.png)

**Comment by Laxystem** [comment]
Probably should have a default player.

**Comment by Gaming32** [comment]
You have no camera in your scene, so nothing will render. The same happens in, say, Unity if you delete the camera. If you go in editor mode, you'll see that the scene is still in fact there.

**Comment by Laxystem** [comment]
> You have no camera in your scene, so nothing will render. The same happens in, say, Unity if you delete the camera. If you go in editor mode, you'll see that the scene is still in fact there.

Oh yes, I realized it right after I posted... 😅

I left it open, saying maybe a default camera should be added if there isn't one.
